version: "3.8"

services:
  tvproxy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tvproxy
    ports:
      - "7860:7860"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
